APP-12/Models/Entities/MyMaskot/Paciente.cs
using APP_12.Models.Entities.MyMaskot.Enum;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace APP_12.Models.Entities.MyMaskot
{
    public class Paciente
    {
        public int PacienteId { get; set; }
        //[Required]
        public int NroRegistro { get; set; }
        //[Required]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public DateTime FechaRegistro { get; set; }
        //[Required]
        public int ClienteId { get; set; }
        public Cliente Cliente { get; set; }
        //[Required]
        public string Nombre { get; set; }
        public Sexo Sexo { get; set; }
        //[Required]
        public int EspecieId { get; set; }
        public Especie Especie { get; set; }

        public int Peso { get; set; }
        public string DatosParticulares { get; set; }
    }
}

APP-12/Controllers/MyMaskot/ConsultaController.cs
using APP_12._Interfaces;
using APP_12.Models.Entities.MyMaskot;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace APP_12.Controllers.MyMaskot
{
    public class ConsultaController : Controller
    {
        IMasterService<Paciente> _pacientes;
        IMasterService<Especie> _especies;
        IMasterService<Cliente> _clientes;
        IMasterService<Consulta> _consultas;

        public ConsultaController(
            IMasterService<Paciente> pacientes,
            IMasterService<Especie> especies,
            IMasterService<Cliente> clientes,
            IMasterService<Consulta> consultas)
        {
            _pacientes = pacientes;
            _especies = especies;
            _clientes = clientes;
            _consultas = consultas;
        }

        // GET: Paciente
        public ActionResult GetByPacienteId(int pacienteId)
        {
            return View(_consultas.Find(x=>x.PacienteId==pacienteId));
        }

        public ActionResult Create(int pacienteId)
        {
            return View(
                new Consulta
                {
                    Fecha = DateTime.Now,
                    PacienteId = pacienteId
                }
            );
        }

        [HttpPost]
        public ActionResult Create(Consulta model)
        {
            var txtRequerido = "Campo Requerido";

            //FechaRegistro
            if (model.Fecha > DateTime.Now)
                ViewData.ModelState.AddModelError("Fecha", "Fecha no válida");

            if (string.IsNullOrEmpty(model.Fecha.ToString()))
                ViewData.ModelState.AddModelError("Fecha", txtRequerido);

            //motivo
            if (string.IsNullOrEmpty(model.Motivo))
                ViewData.ModelState.AddModelError("Motivo", txtRequerido);

            //peso
            if (model.Peso <= 0)
                ViewData.ModelState.AddModelError("Peso", "Inválido");

            //DatosPar
            if (!string.IsNullOrEmpty(model.Comentarios))
                if(model.Comentarios.Length > 200)
                    ViewData.ModelState.AddModelError("Comentarios", "Demasiado largo");
            
            if (ModelState.IsValid)
            {
                if (model.Peso > 0)
                {
                    var paciente = _pacientes.GetById(model.PacienteId);
                    paciente.Peso = model.Peso;
                    _pacientes.Edit(paciente);
                }

                _consultas.Add(model);
                return RedirectToAction("Index","Paciente");
            }
            
            return View(model);
        }
    }
}

APP-12/Controllers/MyMaskot/PacienteController.cs
using APP_12._Interfaces;
using APP_12.Models.Entities.MyMaskot;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace APP_12.Controllers.MyMaskot
{
    public class PacienteController : Controller
    {
        IMasterService<Paciente> _pacientes;
        IMasterService<Especie> _especies;
        IMasterService<Cliente> _clientes;

        public PacienteController(
            IMasterService<Paciente> pacientes,
            IMasterService<Especie> especies,
            IMasterService<Cliente> clientes)
        {
            _pacientes = pacientes;
            _especies = especies;
            _clientes = clientes;
        }

        // GET: Paciente
        public ActionResult Index()
        {
            return View(_pacientes.GetAll());
        }

        public ActionResult Create()
        {
            var especies = _especies.GetAll();
            ViewBag.Especies = new SelectList(especies, "EspecieId", "Name");
            var clientes = _clientes.GetAll();
            ViewBag.Clientes = new SelectList(clientes, "ClienteId", "FullName");

            var nroRegistro = _pacientes.GetAll().Count() > 0 ? _pacientes.GetAll().Last().NroRegistro + 1 : 1;

            return View(
                new Paciente {
                    NroRegistro = nroRegistro,
                    FechaRegistro = DateTime.Now
                }
            );
        }

        [HttpPost]
        public ActionResult Create(Paciente model)
        {
            var txtRequerido = "Campo Requerido";

            //Nro Registro
            if (model.NroRegistro<1)
                ViewData.ModelState.AddModelError("NroRegistro", "Mayor que 0");

            if (string.IsNullOrEmpty(model.NroRegistro.ToString()))
                ViewData.ModelState.AddModelError("NroRegistro", txtRequerido);

            if (_pacientes.Find(x=>x.NroRegistro==model.NroRegistro).Count()>0)
                ViewData.ModelState.AddModelError("NroRegistro", "Ya existe");

            //FechaRegistro
            if (model.FechaRegistro>DateTime.Now)
                ViewData.ModelState.AddModelError("FechaRegistro", "Fecha futura");

            if (string.IsNullOrEmpty(model.FechaRegistro.ToString()))
                ViewData.ModelState.AddModelError("FechaRegistro", txtRequerido);

            //NombreCliente
            if (model.ClienteId <= 0/* || string.IsNullOrEmpty(model.ClienteId.ToString())*/)
                ViewData.ModelState.AddModelError("ClienteId", txtRequerido);

            //NombrePaciente
            if (string.IsNullOrEmpty(model.Nombre))
                ViewData.ModelState.AddModelError("Nombre", txtRequerido);

            //Especie
            if (model.ClienteId <= 0 /*string.IsNullOrEmpty(model.EspecieId.ToString())*/)
                ViewData.ModelState.AddModelError("EspecieId", txtRequerido);

            //Peso
            if(model.Peso<=0)
                ViewData.ModelState.AddModelError("Peso", "Debe ser mayor que 0");

            //DatosPar
            if (!string.IsNullOrEmpty(model.DatosParticulares) && model.DatosParticulares.Length > 200)
                ViewData.ModelState.AddModelError("DatosParticulares", "Demasiado largo");

            if (ModelState.IsValid)
            {
                _pacientes.Add(model);
                return RedirectToAction("Index");
            }

            var especies = _especies.GetAll();
            ViewBag.Especies = new SelectList(especies, "EspecieId", "Name");
            var clientes = _clientes.GetAll();
            ViewBag.Clientes = new SelectList(clientes, "ClienteId", "FullName");
            return View(model);
        }
    }
}

APP-12/Views/Paciente/Create.cshtml
@model APP_12.Models.Entities.MyMaskot.Paciente

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Paciente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NroRegistro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NroRegistro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NroRegistro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaRegistro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaRegistro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaRegistro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClienteId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ClienteId,
                    ViewBag.Clientes as SelectList,
                    "[Cliente]",
                    new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClienteId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EspecieId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EspecieId,
                    ViewBag.Especies as SelectList,
                    "[Especie]",
                    new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EspecieId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Peso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatosParticulares, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatosParticulares, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatosParticulares, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

APP-12/Views/Paciente/Index.cshtml
@model IEnumerable<APP_12.Models.Entities.MyMaskot.Paciente>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NroRegistro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaRegistro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClienteId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EspecieId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Peso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatosParticulares)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NroRegistro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaRegistro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClienteId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EspecieId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Peso)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DatosParticulares)
        </td>
        <td>
            @*Html.ActionLink("Edit", "Edit", new { id=item.PacienteId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PacienteId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.PacienteId })|*@
            @Html.ActionLink("Ver Consultas", "GetByPacienteId","Consulta", new { pacienteId = item.PacienteId },null) | 
            @Html.ActionLink("Nueva Consulta", "Create", "Consulta", new { pacienteId = item.PacienteId }, null)
        </td>
    </tr>
}

</table>