APP-12/Models/Entities/Foro/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace APP_12.Models.Entities
{
    public class Post
    {
        public int PostId { get; set; }
        public Categoria Categoria { get; set; }
        [Required]
        public int CategoriaId { get; set; }
        [Required]
        public string Titulo { get; set; }
        [Required]
        public string Contenido { get; set; }
    }
}

APP-12/Controllers/Foro/ComentarioController.cs
using APP_12._Interfaces;
using APP_12.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace APP_12.Controllers.Foro
{
    public class ComentarioController : Controller
    {
        IMasterService<Comentario> _comentarios;

        public ComentarioController(IMasterService<Comentario> comentarios)
        {
            _comentarios = comentarios;
        }

        public ActionResult GetByPostId(int postId)
        {
            return View(_comentarios.Find(x=>x.PostId==postId));
        }

        public ActionResult Create(int postId)
        {
            return View(new Comentario { PostId = postId});
        }

        [HttpPost]
        public ActionResult Create(Comentario model)
        {
            if (ModelState.IsValid)
            {
                _comentarios.Add(model);
                return RedirectToAction("Index","Post");
            }
            return View(model);
        }
    }
}

APP-12/Controllers/Foro/PostController.cs
using APP_12._Interfaces;
using APP_12.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace APP_12.Controllers.Foro
{
    public class PostController : Controller
    {
        IMasterService<Post> _posts;
        IMasterService<Categoria> _categorias;

        public PostController(
            IMasterService<Post> posts,
            IMasterService<Categoria> categorias)
        {
            _posts = posts;
            _categorias = categorias;
        }

        // GET: Post
        public ActionResult Index()
        {
            return View(_posts.GetAll());
        }
        
        public ActionResult Create()
        {
            var categorias = _categorias.GetAll();
            ViewBag.Categorias = new SelectList(categorias, "CategoriaId", "Nombre");

            return View();
        }

        [HttpPost]
        public ActionResult Create(Post model)
        {
            if(string.IsNullOrEmpty(model.Contenido))
                this.ViewData.ModelState.AddModelError("Contenido", "No puede ser nulo.");
            
            if (ModelState.IsValid)
            {
                _posts.Add(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

APP-12/Views/Post/Create.cshtml
@model APP_12.Models.Entities.Post

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CategoriaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoriaId,
                    ViewBag.Categorias as SelectList,
                    "[Categorìa]",
                    new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contenido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contenido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contenido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

APP-12/Views/Post/Index.cshtml
@model IEnumerable<APP_12.Models.Entities.Post>

@{
    ViewBag.Title = "Posts";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@foreach (var item in Model)
{
    <div class="alert alert-success">
        <p>
            <i> @Html.DisplayFor(modelItem => item.Categoria.Nombre)</i>
        </p>
        <p>
            <strong>@Html.DisplayFor(modelItem => item.Titulo)</strong>
        </p>
        <p>
            @Html.DisplayFor(modelItem => item.Contenido)
        </p>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = item.PostId }) |
            @Html.ActionLink("Details", "Details", new { id = item.PostId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.PostId }) |
            @Html.ActionLink("CreateComment", "Create", "Comentario", new { postId = item.PostId },null) |
            @Html.ActionLink("ViewComments", "GetByPostId", "Comentario" , new { postId = item.PostId },null)
        </p>
    </div>
}